name: go fmt

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.17

#    - name: Copy source
#      run: cp -r pkg pkg-old

    - name: Check formatting
      uses: Jerome1337/gofmt-action@v1.0.4
      with:
        gofmt-path: './pkg'

#    - name: Check Formatting
#      run: diff pkg pkg-old
